# This workflow will build a .NET project and deploy WebApplicationTest1 to an IIS application named test1
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      restore:
        description: "Set to 'true' if you want to restore from local backup instead of deploying new changes."
        required: false
        default: "false"    

jobs:

  build_and_test:
    if: ${{ github.event.inputs.restore != 'true' }}
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore WebApplicationTest1
    - name: Build
      run: |
        dotnet build WebApplicationTest1 --configuration Release --no-restore
        dotnet build TestProject1 --configuration Release --no-restore
    - name: Test (with coverage threshold)
      # Use Coverlet integration to enforce a coverage threshold.
      run: |
        dotnet test TestProject1 --configuration Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestProject1/coverage.opencover.xml /p:Threshold=80 /p:ThresholdType=line /p:ThresholdStat=average
    - name: Publish WebApplicationTest1
      run: dotnet publish WebApplicationTest1 --configuration Release --output publish_output      
    # Use the "Configure the .NET appsettings.tmpl.json" action to replace values.
    - name: Configure the .NET appsettings
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: 'publish_output/appsettings.json'
        keyname1: 'ConnectionStrings'
        keyname2: 'DefaultConnection'
        valuetoset: 'Server=production-server;Database=production-database;Trusted_Connection=True;'
        
  deploy:
    runs-on: self-hosted
    needs: build_and_test
    if: ${{ github.event.inputs.restore != 'true' }}
    steps:
    - name: Backup current production
      shell: powershell
      run: |
          $backupDir = 'D:\backup\test1'
          
          # Clear out the old backup, if any
          if (Test-Path $backupDir) {
            Remove-Item $backupDir -Recurse -Force
          }

          # Create the directory fresh
          New-Item -ItemType Directory -Path $backupDir | Out-Null

          # Copy the current production files
          robocopy "C:\inetpub\wwwroot\test1" $backupDir /E
          if ($LASTEXITCODE -lt 8) { exit 0 } else { exit $LASTEXITCODE }  
          
    - name: Deploy to IIS
      shell: powershell
      run: |
        robocopy publish_output "C:\inetpub\wwwroot\test1" /MIR
        if ($LASTEXITCODE -lt 8) { exit 0 } else { exit $LASTEXITCODE }

  restore_backup:
    runs-on: self-hosted
    if: ${{ github.event.inputs.restore == 'true' }}
    steps:
      - name: Restore backup to production
        shell: powershell
        run: |
          $backupDir = 'D:\backup\test1'
          if (Test-Path $backupDir) {
            robocopy $backupDir "C:\inetpub\wwwroot\test1" /MIR
            if ($LASTEXITCODE -lt 8) { exit 0 } else { exit $LASTEXITCODE }
          }
          else {
            Write-Error "No backup directory found at $backupDir."
          }        
