# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore WebApplicationTest1
    - name: Build
      run: |
        dotnet build WebApplicationTest1 --configuration Release --no-restore
        dotnet build TestProject1 --configuration Release --no-restore
    - name: Test
      run: dotnet test TestProject1  --configuration Release --no-build --verbosity normal
